# Generated by Django 4.2.26 on 2025-12-23 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Login Email')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='AssociationLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Currently Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Association Leadership',
                'verbose_name_plural': 'Association Leadership',
                'ordering': ['position__order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Registration'), ('PROFILE_UPDATE', 'Profile Update'), ('PASSWORD_CHANGE', 'Password Change'), ('ROLE_CHANGE', 'Role Change'), ('LEADERSHIP_ASSIGN', 'Leadership Assignment'), ('LEADERSHIP_REVOKE', 'Leadership Revocation'), ('COMMITTEE_JOIN', 'Committee Join'), ('COMMITTEE_LEAVE', 'Committee Leave'), ('MEMBER_CREATE', 'Member Created'), ('USER_CREATE', 'User Account Created')], max_length=50, verbose_name='Action')),
                ('details', models.JSONField(default=dict, verbose_name='Action Details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Committee Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Committee')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Member', max_length=100, verbose_name='Role in Committee')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Membership')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Committee Membership',
                'verbose_name_plural': 'Committee Memberships',
                'ordering': ['committee__order', 'role', 'user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Event Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(verbose_name='Event Description')),
                ('event_type', models.CharField(choices=[('MEETUP', 'Meetup'), ('SEMINAR', 'Seminar'), ('GET_TOGETHER', 'Get Together'), ('WORKSHOP', 'Workshop'), ('CONFERENCE', 'Conference'), ('OTHER', 'Other')], default='MEETUP', max_length=20, verbose_name='Event Type')),
                ('event_date', models.DateTimeField(verbose_name='Event Date & Time')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date & Time')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('venue', models.TextField(blank=True, verbose_name='Venue Details')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Event Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Event')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Event')),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Attendees')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Registration Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('ATTENDED', 'Attended')], default='PENDING', max_length=20, verbose_name='Registration Status')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Album Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, verbose_name='Album Description')),
                ('album_date', models.DateField(default=django.utils.timezone.now, verbose_name='Album Date')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/covers/', verbose_name='Cover Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Album')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Album')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Album',
                'verbose_name_plural': 'Gallery Albums',
                'ordering': ['-album_date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Image Title')),
                ('image', models.ImageField(upload_to='gallery/images/', verbose_name='Image File')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('taken_date', models.DateField(blank=True, null=True, verbose_name='Date Taken')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company-logos/', verbose_name='Company Logo')),
                ('short_description', models.TextField(help_text='Brief description of the job', verbose_name='Short Description')),
                ('application_url', models.URLField(help_text='External link where candidates can apply', max_length=500, verbose_name='Application URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Advertisement')),
                ('is_expired', models.BooleanField(default=False, verbose_name='Expired')),
                ('posted_date', models.DateTimeField(auto_now_add=True, verbose_name='Posted Date')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Higher number appears first', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Advertisement',
                'verbose_name_plural': 'Job Advertisements',
                'ordering': ['-display_order', '-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PRESIDENT', 'President'), ('VICE_PRESIDENT', 'Vice President'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer'), ('PUBLIC_RELATIONS_OFFICER', 'Public Relations Officer'), ('EXECUTIVE_MEMBER', 'Executive Member')], max_length=50, unique=True, verbose_name='Position Code')),
                ('description', models.TextField(blank=True, verbose_name='Role Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Leadership Position',
                'verbose_name_plural': 'Leadership Positions',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Member ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('student_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Student ID')),
                ('course', models.CharField(blank=True, max_length=100, verbose_name='Course/Department')),
                ('batch', models.CharField(max_length=10, verbose_name='Batch Year')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Graduation Year')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('current_job', models.CharField(blank=True, max_length=200, verbose_name='Current Job/Position')),
                ('current_company', models.CharField(blank=True, max_length=200, verbose_name='Current Company/Organization')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Profile')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub Profile')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio Website')),
                ('is_active_member', models.BooleanField(default=True, verbose_name='Active Member')),
                ('joined_date', models.DateField(default=django.utils.timezone.now, verbose_name='Member Since')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to say')], default='P', max_length=1, verbose_name='Gender')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profile Photo')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public Profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='iuiuapp.campus', verbose_name='Campus')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='iuiuapp.member', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['member__full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_id'], name='iuiuapp_mem_member__ebcf4d_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['email'], name='iuiuapp_mem_email_dcd0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['full_name'], name='iuiuapp_mem_full_na_01fe8c_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['batch'], name='iuiuapp_mem_batch_9f1b16_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['graduation_year'], name='iuiuapp_mem_graduat_34d4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['is_active_member'], name='iuiuapp_mem_is_acti_461b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='leadershipposition',
            index=models.Index(fields=['is_active'], name='iuiuapp_lea_is_acti_b09cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='leadershipposition',
            index=models.Index(fields=['code'], name='iuiuapp_lea_code_446206_idx'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='iuiuapp.galleryalbum', verbose_name='Album'),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_albums', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='iuiuapp.event', verbose_name='Related Event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='iuiuapp.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='iuiuapp.member', verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='iuiuapp.committee', verbose_name='Committee'),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['is_active'], name='iuiuapp_com_is_acti_30806f_idx'),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['slug'], name='iuiuapp_com_slug_e55082_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='iuiuapp.member', verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='associationleadership',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='iuiuapp.leadershipposition', verbose_name='Leadership Position'),
        ),
        migrations.AddField(
            model_name='associationleadership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Leader'),
        ),
        migrations.AddField(
            model_name='user',
            name='committees',
            field=models.ManyToManyField(blank=True, related_name='committee_members', through='iuiuapp.CommitteeMembership', to='iuiuapp.committee', verbose_name='Committees'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='iuiuapp.member', verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='iuiuapp.role', verbose_name='User Roles'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_public'], name='iuiuapp_pro_is_publ_9abe7b_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender'], name='iuiuapp_pro_gender_843659_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['album', 'is_featured'], name='iuiuapp_gal_album_i_84fcf0_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['album', 'order'], name='iuiuapp_gal_album_i_698eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['album_date'], name='iuiuapp_gal_album_d_615999_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['is_active'], name='iuiuapp_gal_is_acti_948d96_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['is_featured'], name='iuiuapp_gal_is_feat_f4ee29_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'status'], name='iuiuapp_eve_event_i_79aa63_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['member', 'status'], name='iuiuapp_eve_member__150c9a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'member')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date'], name='iuiuapp_eve_event_d_e16dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active'], name='iuiuapp_eve_is_acti_29abec_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_featured'], name='iuiuapp_eve_is_feat_1283ee_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='iuiuapp_eve_event_t_a3f987_idx'),
        ),
        migrations.AddIndex(
            model_name='committeemembership',
            index=models.Index(fields=['is_active'], name='iuiuapp_com_is_acti_ba5b24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='committeemembership',
            unique_together={('user', 'committee')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action'], name='iuiuapp_aud_user_id_fc13d7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['member', 'action'], name='iuiuapp_aud_member__6bbb45_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='iuiuapp_aud_timesta_d6ed15_idx'),
        ),
        migrations.AddIndex(
            model_name='associationleadership',
            index=models.Index(fields=['is_active'], name='iuiuapp_ass_is_acti_25a0d0_idx'),
        ),
        migrations.AddIndex(
            model_name='associationleadership',
            index=models.Index(fields=['start_date', 'end_date'], name='iuiuapp_ass_start_d_ba417d_idx'),
        ),
        migrations.AddIndex(
            model_name='associationleadership',
            index=models.Index(fields=['user', 'is_active'], name='iuiuapp_ass_user_id_e1a4e6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='iuiuapp_use_email_ccad76_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['member'], name='iuiuapp_use_member__ce99b2_idx'),
        ),
    ]
