# Generated by Django 6.0 on 2025-12-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iuiuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='department',
            new_name='Course',
        ),
    ]
