# Generated by Django 4.2.26 on 2025-12-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iuiuapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='code',
        ),
    ]
