# Generated by Django 6.0 on 2025-12-19 08:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iuiuapp', '0002_rename_department_profile_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Course',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Registration'), ('PROFILE_UPDATE', 'Profile Update'), ('PASSWORD_CHANGE', 'Password Change'), ('ROLE_CHANGE', 'Role Change'), ('LEADERSHIP_ASSIGN', 'Leadership Assignment'), ('LEADERSHIP_REVOKE', 'Leadership Revocation'), ('COMMITTEE_JOIN', 'Committee Join'), ('COMMITTEE_LEAVE', 'Committee Leave')], max_length=50, verbose_name='Action'),
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Committee Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Committee')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='iuiuapp_com_is_acti_30806f_idx'), models.Index(fields=['slug'], name='iuiuapp_com_slug_e55082_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Member', help_text='e.g., Coordinator, Volunteer, Member', max_length=100, verbose_name='Role in Committee')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Membership')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='iuiuapp.committee', verbose_name='Committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Committee Membership',
                'verbose_name_plural': 'Committee Memberships',
                'ordering': ['committee__order', 'role', 'user__full_name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='committees',
            field=models.ManyToManyField(blank=True, related_name='committee_members', through='iuiuapp.CommitteeMembership', to='iuiuapp.committee', verbose_name='Committees'),
        ),
        migrations.CreateModel(
            name='LeadershipPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PRESIDENT', 'President'), ('VICE_PRESIDENT', 'Vice President'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer'), ('PUBLIC_RELATIONS_OFFICER', 'Public Relations Officer'), ('EXECUTIVE_MEMBER', 'Executive Member')], max_length=50, unique=True, verbose_name='Position Code')),
                ('description', models.TextField(blank=True, verbose_name='Role Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Leadership Position',
                'verbose_name_plural': 'Leadership Positions',
                'ordering': ['order', 'code'],
                'indexes': [models.Index(fields=['is_active'], name='iuiuapp_lea_is_acti_b09cc0_idx'), models.Index(fields=['code'], name='iuiuapp_lea_code_446206_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssociationLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck when the leader resigns or completes term', verbose_name='Currently Active')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this leadership term', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Leader')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='iuiuapp.leadershipposition', verbose_name='Leadership Position')),
            ],
            options={
                'verbose_name': 'Association Leadership',
                'verbose_name_plural': 'Association Leadership',
                'ordering': ['position__order', '-start_date'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, help_text='e.g., Computer Science, Business Administration', max_length=100, verbose_name='Course/Department'),
        ),
        migrations.AddIndex(
            model_name='committeemembership',
            index=models.Index(fields=['is_active'], name='iuiuapp_com_is_acti_ba5b24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='committeemembership',
            unique_together={('user', 'committee')},
        ),
        migrations.AddIndex(
            model_name='associationleadership',
            index=models.Index(fields=['is_active'], name='iuiuapp_ass_is_acti_25a0d0_idx'),
        ),
        migrations.AddIndex(
            model_name='associationleadership',
            index=models.Index(fields=['start_date', 'end_date'], name='iuiuapp_ass_start_d_ba417d_idx'),
        ),
        migrations.AddIndex(
            model_name='associationleadership',
            index=models.Index(fields=['user', 'is_active'], name='iuiuapp_ass_user_id_e1a4e6_idx'),
        ),
    ]
