# Generated by Django 4.2.26 on 2025-12-23 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iuiuapp', '0002_remove_campus_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Event Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(verbose_name='Event Description')),
                ('event_type', models.CharField(choices=[('MEETUP', 'Meetup'), ('SEMINAR', 'Seminar'), ('GET_TOGETHER', 'Get Together'), ('WORKSHOP', 'Workshop'), ('CONFERENCE', 'Conference'), ('OTHER', 'Other')], default='MEETUP', max_length=20, verbose_name='Event Type')),
                ('event_date', models.DateTimeField(verbose_name='Event Date & Time')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date & Time')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('venue', models.TextField(blank=True, verbose_name='Venue Details')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Event Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Event')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Event')),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Attendees')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Registration Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Album Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, verbose_name='Album Description')),
                ('album_date', models.DateField(default=django.utils.timezone.now, verbose_name='Album Date')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/covers/', verbose_name='Cover Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Album')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Album')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_albums', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='iuiuapp.event', verbose_name='Related Event')),
            ],
            options={
                'verbose_name': 'Gallery Album',
                'verbose_name_plural': 'Gallery Albums',
                'ordering': ['-album_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('ATTENDED', 'Attended')], default='PENDING', max_length=20, verbose_name='Registration Status')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='iuiuapp.event', verbose_name='Event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='iuiuapp.member', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Image Title')),
                ('image', models.ImageField(upload_to='gallery/images/', verbose_name='Image File')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('taken_date', models.DateField(blank=True, null=True, verbose_name='Date Taken')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='iuiuapp.galleryalbum', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['album', 'is_featured'], name='iuiuapp_gal_album_i_84fcf0_idx'), models.Index(fields=['album', 'order'], name='iuiuapp_gal_album_i_698eaf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['album_date'], name='iuiuapp_gal_album_d_615999_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['is_active'], name='iuiuapp_gal_is_acti_948d96_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['is_featured'], name='iuiuapp_gal_is_feat_f4ee29_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'status'], name='iuiuapp_eve_event_i_79aa63_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['member', 'status'], name='iuiuapp_eve_member__150c9a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'member')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date'], name='iuiuapp_eve_event_d_e16dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active'], name='iuiuapp_eve_is_acti_29abec_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_featured'], name='iuiuapp_eve_is_feat_1283ee_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='iuiuapp_eve_event_t_a3f987_idx'),
        ),
    ]
