# Generated by Django 6.0 on 2025-12-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iuiuapp', '0003_remove_profile_course_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='P', max_length=1, verbose_name='Gender'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender'], name='iuiuapp_pro_gender_843659_idx'),
        ),
    ]
