# Generated by Django 4.2.26 on 2025-12-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iuiuapp', '0003_event_galleryalbum_eventregistration_galleryimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company-logos/', verbose_name='Company Logo')),
                ('short_description', models.TextField(help_text='Brief description of the job', verbose_name='Short Description')),
                ('application_url', models.URLField(help_text='External link where candidates can apply', max_length=500, verbose_name='Application URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Advertisement')),
                ('is_expired', models.BooleanField(default=False, verbose_name='Expired')),
                ('posted_date', models.DateTimeField(auto_now_add=True, verbose_name='Posted Date')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Higher number appears first', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Advertisement',
                'verbose_name_plural': 'Job Advertisements',
                'ordering': ['-display_order', '-posted_date'],
            },
        ),
    ]
