# Generated by Django 6.0.2 on 2026-03-18 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iuiuapp', '0004_blogcategory_blogpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='video Title')),
                ('video', models.ImageField(upload_to='gallery/videos/', verbose_name='video File')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('captured_date', models.DateField(blank=True, null=True, verbose_name='Date Captured')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured video')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='iuiuapp.galleryalbum', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Gallery video',
                'verbose_name_plural': 'Gallery videos',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['album', 'is_featured'], name='iuiuapp_gal_album_i_ab866f_idx'), models.Index(fields=['album', 'order'], name='iuiuapp_gal_album_i_7a90bf_idx')],
            },
        ),
    ]
