# Generated by Django 4.2.26 on 2025-12-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iuiuapp', '0004_jobadvertisement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobadvertisement',
            old_name='application_url',
            new_name='Detailsation_url',
        ),
    ]
