# Generated by Django 6.0.2 on 2026-03-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iuiuapp', '0005_galleryvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryvideo',
            name='video',
            field=models.FileField(upload_to='gallery/videos/', verbose_name='video File'),
        ),
    ]
