# Generated by Django 4.2.26 on 2025-12-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iuiuapp', '0005_rename_application_url_jobadvertisement_detailsation_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobadvertisement',
            old_name='Detailsation_url',
            new_name='application_url',
        ),
    ]
